services:
  db:
    image: postgres:12.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - motorcycle_rental_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U local_cpavalanche" ]
      interval: 2s
      timeout: 5s
      retries: 10

  migrator:
    build:
      context: ./
      dockerfile: src/Core/MotorcycleRental.Core.Migrator/Dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    links:
      - db:db

volumes:
  motorcycle_rental_postgres_data:
    external: true
